name: Memoria
channels:
  - menpo
  - jlaforet
  - cogsci
  - conda-forge
  - defaults
dependencies:
  - pygame=1.9.2a0
  - pyglet=1.2.4
  - alabaster=0.7.10
  - astroid=1.5.3
  - babel=2.5.1
  - backports=1.0
  - backports.functools_lru_cache=1.4
  - backports.shutil_get_terminal_size=1.0.0
  - backports_abc=0.5
  - bleach=2.0.0
  - bzip2=1.0.6
  - ca-certificates=2017.11.5
  - chardet=3.0.4
  - colorama=0.3.9
  - configparser=3.5.0
  - cycler=0.10.0
  - cython=0.24.1
  - decorator=4.1.2
  - docutils=0.14
  - entrypoints=0.2.3
  - enum34=1.1.6
  - et_xmlfile=1.0.1
  - freetype=2.6.3
  - functools32=3.2.3.2
  - future=0.16.0
  - h5py=2.6.0
  - html5lib=1.0.1
  - idna=2.6
  - imagesize=0.7.1
  - ipaddress=1.0.18
  - ipykernel=4.7.0
  - ipython=5.5.0
  - ipython_genutils=0.2.0
  - isort=4.2.15
  - jinja2=2.10
  - jpeg=9b
  - jsonschema=2.5.1
  - jupyter_client=5.2.1
  - jupyter_core=4.4.0
  - lazy-object-proxy=1.3.1
  - libiconv=1.15
  - libpng=1.6.34
  - libtiff=4.0.6
  - libwebp=0.5.2
  - libxml2=2.9.3
  - markupsafe=1.0
  - matplotlib=2.0.0
  - mccabe=0.6.1
  - mistune=0.8.3
  - nbconvert=5.3.1
  - nbformat=4.4.0
  - ndg-httpsclient=0.4.2
  - nibabel=2.0.2
  - numexpr=2.6.4
  - numpydoc=0.7.0
  - opencv=3.2.0
  - openssl=1.0.2n
  - pandas=0.18.1
  - pandoc=2.1.1
  - pandocfilters=1.4.1
  - path.py=10.3.1
  - pathlib2=2.1.0
  - pep8=1.7.1
  - pillow=3.2.0
  - pip=9.0.1
  - prompt_toolkit=1.0.15
  - py=1.4.31
  - pyasn1=0.1.9
  - pycparser=2.14
  - pydicom=0.9.9
  - pyflakes=1.6.0
  - pygments=2.1.3
  - pylint=1.8.1
  - pyopengl=3.1.1a1
  - pyopenssl=16.2.0
  - pyosf=1.0.4
  - pyparsing=2.2.0
  - pyqt=4.11.4
  - pyserial=3.4
  - pytest=2.9.2
  - python=2.7.14
  - python-dateutil=2.6.1
  - pytz=2017.3
  - pyxid=1.0
  - pyyaml=3.11
  - qt=4.8.7
  - qtawesome=0.4.4
  - qtconsole=4.3.1
  - qtpy=1.3.1
  - requests=2.10.0
  - setuptools=38.4.0
  - simplegeneric=0.8.1
  - singledispatch=3.4.0.3
  - sip=4.18
  - six=1.11.0
  - snowballstemmer=1.2.1
  - sphinx_rtd_theme=0.2.4
  - spyder=3.1.4
  - ssl_match_hostname=3.5.0.1
  - subprocess32=3.2.7
  - testpath=0.3.1
  - tornado=4.5.3
  - tqdm=4.7.2
  - traitlets=4.2.1
  - vc=9
  - vs2008_runtime=9.0.30729.6161
  - vs2015_runtime=14.0.25420
  - wcwidth=0.1.7
  - webencodings=0.5
  - wheel=0.30.0
  - win_unicode_console=0.5
  - wincertstore=0.2
  - wrapt=1.10.11
  - yaml=0.1.7
  - zlib=1.2.11
  - certifi=2017.11.5
  - cffi=1.6.0
  - comtypes=0.6.2
  - configobj=5.0.6
  - cryptography=1.4
  - gevent=1.1.1
  - greenlet=0.4.9
  - hdf5=1.8.15.1
  - icc_rt=2017.0.4
  - intel-openmp=2018.0.0
  - jedi=0.8.1
  - mkl=11.3.3
  - msgpack-python=0.4.7
  - numpy=1.11.2
  - pickleshare=0.7.2
  - psutil=4.2.0
  - pytables=3.2.2
  - pyzmq=15.2.0
  - rope=0.9.4
  - scipy=0.17.1
  - seaborn=0.7.0
  - sphinx=1.4.1
  - vs2010_runtime=10.00.40219.1
  - wxpython=3.0
  - xlrd=0.9.4
  - imageio=1.5
  - moviepy=0.2.2.11
  - ffmpeg=2.7.0
  - pip:
    - backports.ssl-match-hostname==3.5.0.1
    - egi==0.9.0
    - glumpy==1.0.6
    - h5pyviewer==0.0.1.6
    - hid==0.1.1
    - jdcal==1.3
    - openpyxl==2.3.5
    - psychopy==1.84.2
    - psychopy-ext==0.6.0.4
    - pyfilesec==0.2.14
    - pyparallel==0.2.2
    - pypiwin32==219
    - pysoundcard==0.5.2
    - pysoundfile==0.8.1
    - python-bidi==0.4.0
    - svgwrite==1.1.7
    - tables==3.2.2
    - triangle==20170429