# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files\component.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_dlg_component(object):
    def setupUi(self, dlg_component):
        dlg_component.setObjectName(_fromUtf8("dlg_component"))
        dlg_component.resize(530, 360)
        dlg_component.setMinimumSize(QtCore.QSize(530, 360))
        dlg_component.setMaximumSize(QtCore.QSize(530, 360))
        self.verticalLayout = QtGui.QVBoxLayout(dlg_component)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gbx_component = QtGui.QGroupBox(dlg_component)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbx_component.sizePolicy().hasHeightForWidth())
        self.gbx_component.setSizePolicy(sizePolicy)
        self.gbx_component.setMinimumSize(QtCore.QSize(0, 120))
        self.gbx_component.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gbx_component.setObjectName(_fromUtf8("gbx_component"))
        self.formLayout_2 = QtGui.QFormLayout(self.gbx_component)
        self.formLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.formLayout_2.setHorizontalSpacing(5)
        self.formLayout_2.setVerticalSpacing(3)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.lbl_name = QtGui.QLabel(self.gbx_component)
        self.lbl_name.setMinimumSize(QtCore.QSize(70, 25))
        self.lbl_name.setMaximumSize(QtCore.QSize(70, 25))
        self.lbl_name.setBaseSize(QtCore.QSize(0, 0))
        self.lbl_name.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_name.setObjectName(_fromUtf8("lbl_name"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.lbl_name)
        self.led_name = QtGui.QLineEdit(self.gbx_component)
        self.led_name.setMinimumSize(QtCore.QSize(0, 25))
        self.led_name.setBaseSize(QtCore.QSize(0, 0))
        self.led_name.setMaxLength(50)
        self.led_name.setObjectName(_fromUtf8("led_name"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.led_name)
        self.lbl_units = QtGui.QLabel(self.gbx_component)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_units.sizePolicy().hasHeightForWidth())
        self.lbl_units.setSizePolicy(sizePolicy)
        self.lbl_units.setMinimumSize(QtCore.QSize(70, 25))
        self.lbl_units.setMaximumSize(QtCore.QSize(70, 25))
        self.lbl_units.setBaseSize(QtCore.QSize(0, 0))
        self.lbl_units.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_units.setObjectName(_fromUtf8("lbl_units"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.lbl_units)
        self.hly_01 = QtGui.QHBoxLayout()
        self.hly_01.setSpacing(5)
        self.hly_01.setObjectName(_fromUtf8("hly_01"))
        self.cmb_units = QtGui.QComboBox(self.gbx_component)
        self.cmb_units.setMinimumSize(QtCore.QSize(160, 25))
        self.cmb_units.setMaximumSize(QtCore.QSize(150, 25))
        self.cmb_units.setObjectName(_fromUtf8("cmb_units"))
        self.hly_01.addWidget(self.cmb_units)
        self.lne_01 = QtGui.QFrame(self.gbx_component)
        self.lne_01.setMinimumSize(QtCore.QSize(20, 0))
        self.lne_01.setFrameShape(QtGui.QFrame.VLine)
        self.lne_01.setFrameShadow(QtGui.QFrame.Sunken)
        self.lne_01.setObjectName(_fromUtf8("lne_01"))
        self.hly_01.addWidget(self.lne_01)
        self.lbl_size = QtGui.QLabel(self.gbx_component)
        self.lbl_size.setMinimumSize(QtCore.QSize(30, 25))
        self.lbl_size.setMaximumSize(QtCore.QSize(30, 25))
        self.lbl_size.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_size.setObjectName(_fromUtf8("lbl_size"))
        self.hly_01.addWidget(self.lbl_size)
        self.dsb_size = QtGui.QDoubleSpinBox(self.gbx_component)
        self.dsb_size.setMinimumSize(QtCore.QSize(125, 25))
        self.dsb_size.setMaximumSize(QtCore.QSize(115, 25))
        self.dsb_size.setObjectName(_fromUtf8("dsb_size"))
        self.hly_01.addWidget(self.dsb_size)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hly_01.addItem(spacerItem)
        self.formLayout_2.setLayout(1, QtGui.QFormLayout.FieldRole, self.hly_01)
        self.lbl_position = QtGui.QLabel(self.gbx_component)
        self.lbl_position.setMinimumSize(QtCore.QSize(70, 25))
        self.lbl_position.setMaximumSize(QtCore.QSize(70, 25))
        self.lbl_position.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_position.setObjectName(_fromUtf8("lbl_position"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.lbl_position)
        self.hly_02 = QtGui.QHBoxLayout()
        self.hly_02.setSpacing(5)
        self.hly_02.setObjectName(_fromUtf8("hly_02"))
        self.lbl_posx = QtGui.QLabel(self.gbx_component)
        self.lbl_posx.setMinimumSize(QtCore.QSize(30, 25))
        self.lbl_posx.setMaximumSize(QtCore.QSize(30, 25))
        self.lbl_posx.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_posx.setObjectName(_fromUtf8("lbl_posx"))
        self.hly_02.addWidget(self.lbl_posx)
        self.dsb_posx = QtGui.QDoubleSpinBox(self.gbx_component)
        self.dsb_posx.setMinimumSize(QtCore.QSize(125, 25))
        self.dsb_posx.setMaximumSize(QtCore.QSize(115, 25))
        self.dsb_posx.setObjectName(_fromUtf8("dsb_posx"))
        self.hly_02.addWidget(self.dsb_posx)
        self.lne_02 = QtGui.QFrame(self.gbx_component)
        self.lne_02.setMinimumSize(QtCore.QSize(20, 0))
        self.lne_02.setFrameShape(QtGui.QFrame.VLine)
        self.lne_02.setFrameShadow(QtGui.QFrame.Sunken)
        self.lne_02.setObjectName(_fromUtf8("lne_02"))
        self.hly_02.addWidget(self.lne_02)
        self.lbl_posy = QtGui.QLabel(self.gbx_component)
        self.lbl_posy.setMinimumSize(QtCore.QSize(30, 25))
        self.lbl_posy.setMaximumSize(QtCore.QSize(30, 25))
        self.lbl_posy.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_posy.setObjectName(_fromUtf8("lbl_posy"))
        self.hly_02.addWidget(self.lbl_posy)
        self.dsb_posy = QtGui.QDoubleSpinBox(self.gbx_component)
        self.dsb_posy.setMinimumSize(QtCore.QSize(125, 25))
        self.dsb_posy.setMaximumSize(QtCore.QSize(115, 25))
        self.dsb_posy.setObjectName(_fromUtf8("dsb_posy"))
        self.hly_02.addWidget(self.dsb_posy)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hly_02.addItem(spacerItem1)
        self.formLayout_2.setLayout(2, QtGui.QFormLayout.FieldRole, self.hly_02)
        self.lbl_orientation = QtGui.QLabel(self.gbx_component)
        self.lbl_orientation.setObjectName(_fromUtf8("lbl_orientation"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.lbl_orientation)
        self.dsb_orientation = QtGui.QDoubleSpinBox(self.gbx_component)
        self.dsb_orientation.setMinimumSize(QtCore.QSize(160, 25))
        self.dsb_orientation.setMaximumSize(QtCore.QSize(150, 25))
        self.dsb_orientation.setObjectName(_fromUtf8("dsb_orientation"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.dsb_orientation)
        self.lbl_type = QtGui.QLabel(self.gbx_component)
        self.lbl_type.setMinimumSize(QtCore.QSize(70, 25))
        self.lbl_type.setMaximumSize(QtCore.QSize(70, 25))
        self.lbl_type.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_type.setObjectName(_fromUtf8("lbl_type"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.lbl_type)
        self.hly_03 = QtGui.QHBoxLayout()
        self.hly_03.setSpacing(5)
        self.hly_03.setObjectName(_fromUtf8("hly_03"))
        self.rbt_shape = QtGui.QRadioButton(self.gbx_component)
        self.rbt_shape.setMinimumSize(QtCore.QSize(100, 25))
        self.rbt_shape.setMaximumSize(QtCore.QSize(150, 25))
        self.rbt_shape.setChecked(True)
        self.rbt_shape.setObjectName(_fromUtf8("rbt_shape"))
        self.gbt_component_type = QtGui.QButtonGroup(dlg_component)
        self.gbt_component_type.setObjectName(_fromUtf8("gbt_component_type"))
        self.gbt_component_type.addButton(self.rbt_shape)
        self.hly_03.addWidget(self.rbt_shape)
        self.rbt_image = QtGui.QRadioButton(self.gbx_component)
        self.rbt_image.setMinimumSize(QtCore.QSize(100, 25))
        self.rbt_image.setMaximumSize(QtCore.QSize(150, 25))
        self.rbt_image.setObjectName(_fromUtf8("rbt_image"))
        self.gbt_component_type.addButton(self.rbt_image)
        self.hly_03.addWidget(self.rbt_image)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hly_03.addItem(spacerItem2)
        self.formLayout_2.setLayout(4, QtGui.QFormLayout.FieldRole, self.hly_03)
        self.verticalLayout.addWidget(self.gbx_component)
        self.hly_04 = QtGui.QHBoxLayout()
        self.hly_04.setObjectName(_fromUtf8("hly_04"))
        self.gbx_shape = QtGui.QGroupBox(dlg_component)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbx_shape.sizePolicy().hasHeightForWidth())
        self.gbx_shape.setSizePolicy(sizePolicy)
        self.gbx_shape.setMinimumSize(QtCore.QSize(0, 0))
        self.gbx_shape.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gbx_shape.setObjectName(_fromUtf8("gbx_shape"))
        self.formLayout = QtGui.QFormLayout(self.gbx_shape)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.lbl_shape = QtGui.QLabel(self.gbx_shape)
        self.lbl_shape.setMinimumSize(QtCore.QSize(50, 25))
        self.lbl_shape.setMaximumSize(QtCore.QSize(50, 25))
        self.lbl_shape.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_shape.setObjectName(_fromUtf8("lbl_shape"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.lbl_shape)
        self.lbl_shape_color = QtGui.QLabel(self.gbx_shape)
        self.lbl_shape_color.setMinimumSize(QtCore.QSize(50, 25))
        self.lbl_shape_color.setMaximumSize(QtCore.QSize(50, 25))
        self.lbl_shape_color.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_shape_color.setObjectName(_fromUtf8("lbl_shape_color"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.lbl_shape_color)
        self.cmb_shape_color = QtGui.QComboBox(self.gbx_shape)
        self.cmb_shape_color.setMinimumSize(QtCore.QSize(0, 25))
        self.cmb_shape_color.setMaximumSize(QtCore.QSize(150, 25))
        self.cmb_shape_color.setObjectName(_fromUtf8("cmb_shape_color"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.cmb_shape_color)
        self.cmb_shape = QtGui.QComboBox(self.gbx_shape)
        self.cmb_shape.setMinimumSize(QtCore.QSize(0, 25))
        self.cmb_shape.setMaximumSize(QtCore.QSize(150, 25))
        self.cmb_shape.setObjectName(_fromUtf8("cmb_shape"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.cmb_shape)
        self.hly_04.addWidget(self.gbx_shape)
        self.gbx_image = QtGui.QGroupBox(dlg_component)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbx_image.sizePolicy().hasHeightForWidth())
        self.gbx_image.setSizePolicy(sizePolicy)
        self.gbx_image.setObjectName(_fromUtf8("gbx_image"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.gbx_image)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.lbl_image_status = QtGui.QLabel(self.gbx_image)
        self.lbl_image_status.setMinimumSize(QtCore.QSize(120, 60))
        self.lbl_image_status.setMaximumSize(QtCore.QSize(70, 60))
        self.lbl_image_status.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_image_status.setObjectName(_fromUtf8("lbl_image_status"))
        self.horizontalLayout_4.addWidget(self.lbl_image_status)
        self.vly_01 = QtGui.QVBoxLayout()
        self.vly_01.setSpacing(3)
        self.vly_01.setObjectName(_fromUtf8("vly_01"))
        self.pbt_image_open = QtGui.QPushButton(self.gbx_image)
        self.pbt_image_open.setMinimumSize(QtCore.QSize(0, 25))
        self.pbt_image_open.setMaximumSize(QtCore.QSize(16777215, 25))
        self.pbt_image_open.setObjectName(_fromUtf8("pbt_image_open"))
        self.vly_01.addWidget(self.pbt_image_open)
        self.pbt_image_zoom = QtGui.QPushButton(self.gbx_image)
        self.pbt_image_zoom.setMinimumSize(QtCore.QSize(0, 25))
        self.pbt_image_zoom.setMaximumSize(QtCore.QSize(16777215, 25))
        self.pbt_image_zoom.setObjectName(_fromUtf8("pbt_image_zoom"))
        self.vly_01.addWidget(self.pbt_image_zoom)
        self.horizontalLayout_4.addLayout(self.vly_01)
        self.hly_04.addWidget(self.gbx_image)
        self.verticalLayout.addLayout(self.hly_04)
        self.hly_05 = QtGui.QHBoxLayout()
        self.hly_05.setObjectName(_fromUtf8("hly_05"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hly_05.addItem(spacerItem3)
        self.pbt_preview = QtGui.QPushButton(dlg_component)
        self.pbt_preview.setMinimumSize(QtCore.QSize(155, 25))
        self.pbt_preview.setMaximumSize(QtCore.QSize(155, 25))
        self.pbt_preview.setObjectName(_fromUtf8("pbt_preview"))
        self.hly_05.addWidget(self.pbt_preview)
        self.verticalLayout.addLayout(self.hly_05)
        self.bbt_save = QtGui.QDialogButtonBox(dlg_component)
        self.bbt_save.setMinimumSize(QtCore.QSize(0, 25))
        self.bbt_save.setMaximumSize(QtCore.QSize(16777215, 25))
        self.bbt_save.setOrientation(QtCore.Qt.Horizontal)
        self.bbt_save.setStandardButtons(QtGui.QDialogButtonBox.Close|QtGui.QDialogButtonBox.Save)
        self.bbt_save.setObjectName(_fromUtf8("bbt_save"))
        self.verticalLayout.addWidget(self.bbt_save)
        self.bbt_save.raise_()
        self.gbx_component.raise_()

        self.retranslateUi(dlg_component)
        QtCore.QObject.connect(self.bbt_save, QtCore.SIGNAL(_fromUtf8("accepted()")), dlg_component.accept)
        QtCore.QObject.connect(self.bbt_save, QtCore.SIGNAL(_fromUtf8("rejected()")), dlg_component.reject)
        QtCore.QMetaObject.connectSlotsByName(dlg_component)

    def retranslateUi(self, dlg_component):
        dlg_component.setWindowTitle(_translate("dlg_component", "Component", None))
        self.gbx_component.setTitle(_translate("dlg_component", "Component", None))
        self.lbl_name.setText(_translate("dlg_component", "Name:", None))
        self.lbl_units.setText(_translate("dlg_component", "Units:", None))
        self.lbl_size.setText(_translate("dlg_component", "Size:", None))
        self.lbl_position.setText(_translate("dlg_component", "Position:", None))
        self.lbl_posx.setText(_translate("dlg_component", "X:", None))
        self.lbl_posy.setText(_translate("dlg_component", "Y:", None))
        self.lbl_orientation.setText(_translate("dlg_component", "Rotation:", None))
        self.lbl_type.setText(_translate("dlg_component", "Type:", None))
        self.rbt_shape.setText(_translate("dlg_component", "Shape", None))
        self.rbt_image.setText(_translate("dlg_component", "Image", None))
        self.gbx_shape.setTitle(_translate("dlg_component", "Shape", None))
        self.lbl_shape.setText(_translate("dlg_component", "Shape:", None))
        self.lbl_shape_color.setText(_translate("dlg_component", "Color:", None))
        self.gbx_image.setTitle(_translate("dlg_component", "Image", None))
        self.lbl_image_status.setText(_translate("dlg_component", "No Image", None))
        self.pbt_image_open.setText(_translate("dlg_component", "Open", None))
        self.pbt_image_zoom.setText(_translate("dlg_component", "Zoom", None))
        self.pbt_preview.setText(_translate("dlg_component", "PreView", None))

