# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files\configuration.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_dlg_configuration(object):
    def setupUi(self):
        self.setObjectName(_fromUtf8("dlg_configuration"))
        self.resize(530, 230)
        self.setMinimumSize(QtCore.QSize(530, 230))
        self.setMaximumSize(QtCore.QSize(530, 230))
        self.verticalLayout = QtGui.QVBoxLayout(self)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gbox_configuration = QtGui.QGroupBox(self)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbox_configuration.sizePolicy().hasHeightForWidth())
        self.gbox_configuration.setSizePolicy(sizePolicy)
        self.gbox_configuration.setMinimumSize(QtCore.QSize(0, 180))
        self.gbox_configuration.setMaximumSize(QtCore.QSize(16777215, 180))
        self.gbox_configuration.setObjectName(_fromUtf8("gbox_configuration"))
        self.formLayout_2 = QtGui.QFormLayout(self.gbox_configuration)
        self.formLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.formLayout_2.setHorizontalSpacing(5)
        self.formLayout_2.setVerticalSpacing(3)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.lbl_name = QtGui.QLabel(self.gbox_configuration)
        self.lbl_name.setMinimumSize(QtCore.QSize(70, 25))
        self.lbl_name.setMaximumSize(QtCore.QSize(70, 25))
        self.lbl_name.setBaseSize(QtCore.QSize(0, 0))
        self.lbl_name.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_name.setObjectName(_fromUtf8("lbl_name"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.lbl_name)
        self.lbl_screen = QtGui.QLabel(self.gbox_configuration)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_screen.sizePolicy().hasHeightForWidth())
        self.lbl_screen.setSizePolicy(sizePolicy)
        self.lbl_screen.setMinimumSize(QtCore.QSize(70, 25))
        self.lbl_screen.setMaximumSize(QtCore.QSize(70, 25))
        self.lbl_screen.setBaseSize(QtCore.QSize(0, 0))
        self.lbl_screen.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_screen.setObjectName(_fromUtf8("lbl_screen"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.lbl_screen)
        self.lbl_monitor = QtGui.QLabel(self.gbox_configuration)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_monitor.sizePolicy().hasHeightForWidth())
        self.lbl_monitor.setSizePolicy(sizePolicy)
        self.lbl_monitor.setMinimumSize(QtCore.QSize(70, 25))
        self.lbl_monitor.setMaximumSize(QtCore.QSize(70, 25))
        self.lbl_monitor.setBaseSize(QtCore.QSize(0, 0))
        self.lbl_monitor.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_monitor.setObjectName(_fromUtf8("lbl_monitor"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.lbl_monitor)
        self.lbl_tracker = QtGui.QLabel(self.gbox_configuration)
        self.lbl_tracker.setMinimumSize(QtCore.QSize(70, 25))
        self.lbl_tracker.setMaximumSize(QtCore.QSize(70, 25))
        self.lbl_tracker.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_tracker.setObjectName(_fromUtf8("lbl_tracker"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.lbl_tracker)
        self.led_name = QtGui.QLineEdit(self.gbox_configuration)
        self.led_name.setMinimumSize(QtCore.QSize(0, 25))
        self.led_name.setMaximumSize(QtCore.QSize(16777215, 25))
        self.led_name.setObjectName(_fromUtf8("led_name"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.led_name)
        self.lbl_path = QtGui.QLabel(self.gbox_configuration)
        self.lbl_path.setMinimumSize(QtCore.QSize(70, 25))
        self.lbl_path.setMaximumSize(QtCore.QSize(70, 25))
        self.lbl_path.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_path.setObjectName(_fromUtf8("lbl_path"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.lbl_path)
        self.cmb_monitor = QtGui.QComboBox(self.gbox_configuration)
        self.cmb_monitor.setMinimumSize(QtCore.QSize(0, 25))
        self.cmb_monitor.setMaximumSize(QtCore.QSize(16777215, 25))
        self.cmb_monitor.setObjectName(_fromUtf8("cmb_monitor"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.cmb_monitor)
        self.cmb_screen = QtGui.QComboBox(self.gbox_configuration)
        self.cmb_screen.setMinimumSize(QtCore.QSize(0, 25))
        self.cmb_screen.setMaximumSize(QtCore.QSize(16777215, 25))
        self.cmb_screen.setObjectName(_fromUtf8("cmb_screen"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.cmb_screen)
        self.cmb_tracker = QtGui.QComboBox(self.gbox_configuration)
        self.cmb_tracker.setMinimumSize(QtCore.QSize(0, 25))
        self.cmb_tracker.setMaximumSize(QtCore.QSize(16777215, 25))
        self.cmb_tracker.setObjectName(_fromUtf8("cmb_tracker"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.cmb_tracker)
        self.hly_01 = QtGui.QHBoxLayout()
        self.hly_01.setObjectName(_fromUtf8("hly_01"))
        self.led_path = QtGui.QLineEdit(self.gbox_configuration)
        self.led_path.setMinimumSize(QtCore.QSize(0, 25))
        self.led_path.setMaximumSize(QtCore.QSize(16777215, 25))
        self.led_path.setReadOnly(True)
        self.led_path.setObjectName(_fromUtf8("led_path"))
        self.hly_01.addWidget(self.led_path)
        self.pbt_path_browse = QtGui.QPushButton(self.gbox_configuration)
        self.pbt_path_browse.setMinimumSize(QtCore.QSize(0, 25))
        self.pbt_path_browse.setMaximumSize(QtCore.QSize(16777215, 25))
        self.pbt_path_browse.setObjectName(_fromUtf8("pbt_path_browse"))
        self.hly_01.addWidget(self.pbt_path_browse)
        self.formLayout_2.setLayout(1, QtGui.QFormLayout.FieldRole, self.hly_01)
        self.verticalLayout.addWidget(self.gbox_configuration)
        self.bbt_save = QtGui.QDialogButtonBox(self)
        self.bbt_save.setMinimumSize(QtCore.QSize(0, 25))
        self.bbt_save.setMaximumSize(QtCore.QSize(16777215, 25))
        self.bbt_save.setOrientation(QtCore.Qt.Horizontal)
        self.bbt_save.setStandardButtons(QtGui.QDialogButtonBox.Close|QtGui.QDialogButtonBox.Save)
        self.bbt_save.setObjectName(_fromUtf8("bbt_save"))
        self.verticalLayout.addWidget(self.bbt_save)

        self.retranslateUi()
        QtCore.QObject.connect(self.bbt_save, QtCore.SIGNAL(_fromUtf8("accepted()")), self.accept)
        QtCore.QObject.connect(self.bbt_save, QtCore.SIGNAL(_fromUtf8("rejected()")), self.reject)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        self.setWindowTitle(_translate("dlg_configuration", "Configuration Profile", None))
        self.gbox_configuration.setTitle(_translate("dlg_configuration", "Configuration Profile", None))
        self.lbl_name.setText(_translate("dlg_configuration", "Name:", None))
        self.lbl_screen.setText(_translate("dlg_configuration", "Screen:", None))
        self.lbl_monitor.setText(_translate("dlg_configuration", "Monitor:", None))
        self.lbl_tracker.setText(_translate("dlg_configuration", "Eye Tracker:", None))
        self.lbl_path.setText(_translate("dlg_configuration", "Events Path:", None))
        self.pbt_path_browse.setText(_translate("dlg_configuration", "Browse...", None))

