# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files\frame.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_dlg_frame(object):
    def setupUi(self, dlg_frame):
        dlg_frame.setObjectName(_fromUtf8("dlg_frame"))
        dlg_frame.resize(530, 500)
        dlg_frame.setMinimumSize(QtCore.QSize(530, 380))
        dlg_frame.setMaximumSize(QtCore.QSize(530, 850))
        self.verticalLayout = QtGui.QVBoxLayout(dlg_frame)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gbx_frame = QtGui.QGroupBox(dlg_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbx_frame.sizePolicy().hasHeightForWidth())
        self.gbx_frame.setSizePolicy(sizePolicy)
        self.gbx_frame.setMinimumSize(QtCore.QSize(0, 120))
        self.gbx_frame.setMaximumSize(QtCore.QSize(16777215, 120))
        self.gbx_frame.setObjectName(_fromUtf8("gbx_frame"))
        self.formLayout_2 = QtGui.QFormLayout(self.gbx_frame)
        self.formLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.formLayout_2.setHorizontalSpacing(5)
        self.formLayout_2.setVerticalSpacing(3)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.lbl_name = QtGui.QLabel(self.gbx_frame)
        self.lbl_name.setMinimumSize(QtCore.QSize(70, 25))
        self.lbl_name.setMaximumSize(QtCore.QSize(70, 25))
        self.lbl_name.setBaseSize(QtCore.QSize(0, 0))
        self.lbl_name.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_name.setObjectName(_fromUtf8("lbl_name"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.lbl_name)
        self.led_name = QtGui.QLineEdit(self.gbx_frame)
        self.led_name.setMinimumSize(QtCore.QSize(0, 25))
        self.led_name.setBaseSize(QtCore.QSize(0, 0))
        self.led_name.setMaxLength(50)
        self.led_name.setObjectName(_fromUtf8("led_name"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.led_name)
        self.lbl_background = QtGui.QLabel(self.gbx_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_background.sizePolicy().hasHeightForWidth())
        self.lbl_background.setSizePolicy(sizePolicy)
        self.lbl_background.setMinimumSize(QtCore.QSize(70, 25))
        self.lbl_background.setMaximumSize(QtCore.QSize(70, 25))
        self.lbl_background.setBaseSize(QtCore.QSize(0, 0))
        self.lbl_background.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_background.setObjectName(_fromUtf8("lbl_background"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.lbl_background)
        self.cmb_background = QtGui.QComboBox(self.gbx_frame)
        self.cmb_background.setMinimumSize(QtCore.QSize(0, 25))
        self.cmb_background.setMaximumSize(QtCore.QSize(200, 25))
        self.cmb_background.setObjectName(_fromUtf8("cmb_background"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.cmb_background)
        self.lbl_type = QtGui.QLabel(self.gbx_frame)
        self.lbl_type.setMinimumSize(QtCore.QSize(70, 25))
        self.lbl_type.setMaximumSize(QtCore.QSize(70, 25))
        self.lbl_type.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_type.setObjectName(_fromUtf8("lbl_type"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.lbl_type)
        self.hly_01 = QtGui.QHBoxLayout()
        self.hly_01.setObjectName(_fromUtf8("hly_01"))
        self.rbt_time = QtGui.QRadioButton(self.gbx_frame)
        self.rbt_time.setMinimumSize(QtCore.QSize(150, 25))
        self.rbt_time.setMaximumSize(QtCore.QSize(150, 25))
        self.rbt_time.setChecked(True)
        self.rbt_time.setObjectName(_fromUtf8("rbt_time"))
        self.gbt_frame_type = QtGui.QButtonGroup(dlg_frame)
        self.gbt_frame_type.setObjectName(_fromUtf8("gbt_frame_type"))
        self.gbt_frame_type.addButton(self.rbt_time)
        self.hly_01.addWidget(self.rbt_time)
        self.rbt_task = QtGui.QRadioButton(self.gbx_frame)
        self.rbt_task.setMinimumSize(QtCore.QSize(150, 25))
        self.rbt_task.setMaximumSize(QtCore.QSize(150, 25))
        self.rbt_task.setObjectName(_fromUtf8("rbt_task"))
        self.gbt_frame_type.addButton(self.rbt_task)
        self.hly_01.addWidget(self.rbt_task)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hly_01.addItem(spacerItem)
        self.formLayout_2.setLayout(1, QtGui.QFormLayout.FieldRole, self.hly_01)
        self.verticalLayout.addWidget(self.gbx_frame)
        self.hly_02 = QtGui.QHBoxLayout()
        self.hly_02.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.hly_02.setSpacing(5)
        self.hly_02.setObjectName(_fromUtf8("hly_02"))
        self.gbx_timed = QtGui.QGroupBox(dlg_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbx_timed.sizePolicy().hasHeightForWidth())
        self.gbx_timed.setSizePolicy(sizePolicy)
        self.gbx_timed.setMinimumSize(QtCore.QSize(0, 90))
        self.gbx_timed.setMaximumSize(QtCore.QSize(16777215, 90))
        self.gbx_timed.setObjectName(_fromUtf8("gbx_timed"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.gbx_timed)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.fly_02 = QtGui.QFormLayout()
        self.fly_02.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.fly_02.setObjectName(_fromUtf8("fly_02"))
        self.lbl_time = QtGui.QLabel(self.gbx_timed)
        self.lbl_time.setMinimumSize(QtCore.QSize(60, 25))
        self.lbl_time.setMaximumSize(QtCore.QSize(50, 25))
        self.lbl_time.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_time.setObjectName(_fromUtf8("lbl_time"))
        self.fly_02.setWidget(0, QtGui.QFormLayout.LabelRole, self.lbl_time)
        self.dsb_time = QtGui.QDoubleSpinBox(self.gbx_timed)
        self.dsb_time.setMinimumSize(QtCore.QSize(100, 25))
        self.dsb_time.setMaximumSize(QtCore.QSize(16777215, 25))
        self.dsb_time.setObjectName(_fromUtf8("dsb_time"))
        self.fly_02.setWidget(0, QtGui.QFormLayout.FieldRole, self.dsb_time)
        self.verticalLayout_2.addLayout(self.fly_02)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.hly_02.addWidget(self.gbx_timed)
        self.gbx_task = QtGui.QGroupBox(dlg_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbx_task.sizePolicy().hasHeightForWidth())
        self.gbx_task.setSizePolicy(sizePolicy)
        self.gbx_task.setMinimumSize(QtCore.QSize(0, 90))
        self.gbx_task.setMaximumSize(QtCore.QSize(16777215, 90))
        self.gbx_task.setObjectName(_fromUtf8("gbx_task"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.gbx_task)
        self.verticalLayout_3.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.verticalLayout_3.setSpacing(5)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.fly_03 = QtGui.QFormLayout()
        self.fly_03.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.fly_03.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.fly_03.setVerticalSpacing(6)
        self.fly_03.setObjectName(_fromUtf8("fly_03"))
        self.led_keys_allowed = QtGui.QLineEdit(self.gbx_task)
        self.led_keys_allowed.setMinimumSize(QtCore.QSize(200, 25))
        self.led_keys_allowed.setMaximumSize(QtCore.QSize(16777215, 25))
        self.led_keys_allowed.setObjectName(_fromUtf8("led_keys_allowed"))
        self.fly_03.setWidget(0, QtGui.QFormLayout.FieldRole, self.led_keys_allowed)
        self.led_keys_selected = QtGui.QLineEdit(self.gbx_task)
        self.led_keys_selected.setMinimumSize(QtCore.QSize(200, 25))
        self.led_keys_selected.setMaximumSize(QtCore.QSize(16777215, 25))
        self.led_keys_selected.setObjectName(_fromUtf8("led_keys_selected"))
        self.fly_03.setWidget(1, QtGui.QFormLayout.FieldRole, self.led_keys_selected)
        self.lbl_keys_allowed = QtGui.QLabel(self.gbx_task)
        self.lbl_keys_allowed.setMinimumSize(QtCore.QSize(70, 25))
        self.lbl_keys_allowed.setMaximumSize(QtCore.QSize(70, 25))
        self.lbl_keys_allowed.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_keys_allowed.setObjectName(_fromUtf8("lbl_keys_allowed"))
        self.fly_03.setWidget(0, QtGui.QFormLayout.LabelRole, self.lbl_keys_allowed)
        self.lbl_keys_selected = QtGui.QLabel(self.gbx_task)
        self.lbl_keys_selected.setMinimumSize(QtCore.QSize(70, 25))
        self.lbl_keys_selected.setMaximumSize(QtCore.QSize(70, 25))
        self.lbl_keys_selected.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_keys_selected.setObjectName(_fromUtf8("lbl_keys_selected"))
        self.fly_03.setWidget(1, QtGui.QFormLayout.LabelRole, self.lbl_keys_selected)
        self.verticalLayout_3.addLayout(self.fly_03)
        self.hly_02.addWidget(self.gbx_task)
        self.verticalLayout.addLayout(self.hly_02)
        self.gbx_components = QtGui.QGroupBox(dlg_frame)
        self.gbx_components.setMinimumSize(QtCore.QSize(0, 180))
        self.gbx_components.setObjectName(_fromUtf8("gbx_components"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.gbx_components)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tbv = QtGui.QTableView(self.gbx_components)
        self.tbv.setMinimumSize(QtCore.QSize(380, 120))
        self.tbv.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tbv.setObjectName(_fromUtf8("tbv"))
        self.horizontalLayout.addWidget(self.tbv)
        self.vly_01 = QtGui.QVBoxLayout()
        self.vly_01.setSpacing(3)
        self.vly_01.setObjectName(_fromUtf8("vly_01"))
        self.pbt_new = QtGui.QPushButton(self.gbx_components)
        self.pbt_new.setMinimumSize(QtCore.QSize(80, 25))
        self.pbt_new.setMaximumSize(QtCore.QSize(16777215, 25))
        self.pbt_new.setObjectName(_fromUtf8("pbt_new"))
        self.vly_01.addWidget(self.pbt_new)
        self.hly_04 = QtGui.QHBoxLayout()
        self.hly_04.setSpacing(4)
        self.hly_04.setObjectName(_fromUtf8("hly_04"))
        self.pbt_up = QtGui.QPushButton(self.gbx_components)
        self.pbt_up.setMinimumSize(QtCore.QSize(38, 25))
        self.pbt_up.setMaximumSize(QtCore.QSize(38, 25))
        self.pbt_up.setObjectName(_fromUtf8("pbt_up"))
        self.hly_04.addWidget(self.pbt_up)
        self.pbt_down = QtGui.QPushButton(self.gbx_components)
        self.pbt_down.setMinimumSize(QtCore.QSize(38, 25))
        self.pbt_down.setMaximumSize(QtCore.QSize(38, 25))
        self.pbt_down.setObjectName(_fromUtf8("pbt_down"))
        self.hly_04.addWidget(self.pbt_down)
        self.vly_01.addLayout(self.hly_04)
        self.pbt_edit = QtGui.QPushButton(self.gbx_components)
        self.pbt_edit.setMinimumSize(QtCore.QSize(80, 25))
        self.pbt_edit.setMaximumSize(QtCore.QSize(16777215, 25))
        self.pbt_edit.setObjectName(_fromUtf8("pbt_edit"))
        self.vly_01.addWidget(self.pbt_edit)
        self.pbt_copy = QtGui.QPushButton(self.gbx_components)
        self.pbt_copy.setMinimumSize(QtCore.QSize(0, 25))
        self.pbt_copy.setMaximumSize(QtCore.QSize(16777215, 25))
        self.pbt_copy.setObjectName(_fromUtf8("pbt_copy"))
        self.vly_01.addWidget(self.pbt_copy)
        self.pbt_remove = QtGui.QPushButton(self.gbx_components)
        self.pbt_remove.setMinimumSize(QtCore.QSize(80, 25))
        self.pbt_remove.setMaximumSize(QtCore.QSize(16777215, 25))
        self.pbt_remove.setObjectName(_fromUtf8("pbt_remove"))
        self.vly_01.addWidget(self.pbt_remove)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vly_01.addItem(spacerItem3)
        self.horizontalLayout.addLayout(self.vly_01)
        self.verticalLayout.addWidget(self.gbx_components)
        self.hly_03 = QtGui.QHBoxLayout()
        self.hly_03.setObjectName(_fromUtf8("hly_03"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hly_03.addItem(spacerItem4)
        self.pbt_preview = QtGui.QPushButton(dlg_frame)
        self.pbt_preview.setMinimumSize(QtCore.QSize(155, 25))
        self.pbt_preview.setMaximumSize(QtCore.QSize(155, 25))
        self.pbt_preview.setObjectName(_fromUtf8("pbt_preview"))
        self.hly_03.addWidget(self.pbt_preview)
        self.verticalLayout.addLayout(self.hly_03)
        self.bbt_save = QtGui.QDialogButtonBox(dlg_frame)
        self.bbt_save.setOrientation(QtCore.Qt.Horizontal)
        self.bbt_save.setStandardButtons(QtGui.QDialogButtonBox.Close|QtGui.QDialogButtonBox.Save)
        self.bbt_save.setObjectName(_fromUtf8("bbt_save"))
        self.verticalLayout.addWidget(self.bbt_save)
        self.bbt_save.raise_()
        self.gbx_frame.raise_()
        self.gbx_components.raise_()

        self.retranslateUi(dlg_frame)
        QtCore.QObject.connect(self.bbt_save, QtCore.SIGNAL(_fromUtf8("accepted()")), dlg_frame.accept)
        QtCore.QObject.connect(self.bbt_save, QtCore.SIGNAL(_fromUtf8("rejected()")), dlg_frame.reject)
        QtCore.QMetaObject.connectSlotsByName(dlg_frame)

    def retranslateUi(self, dlg_frame):
        dlg_frame.setWindowTitle(_translate("dlg_frame", "Frame", None))
        self.gbx_frame.setTitle(_translate("dlg_frame", "Frame", None))
        self.lbl_name.setText(_translate("dlg_frame", "Name:", None))
        self.lbl_background.setText(_translate("dlg_frame", "Background:", None))
        self.lbl_type.setText(_translate("dlg_frame", "Type:", None))
        self.rbt_time.setText(_translate("dlg_frame", "Timed", None))
        self.rbt_task.setText(_translate("dlg_frame", "User response / Task", None))
        self.gbx_timed.setTitle(_translate("dlg_frame", "Timed", None))
        self.lbl_time.setText(_translate("dlg_frame", "Frame time:", None))
        self.gbx_task.setTitle(_translate("dlg_frame", "Task", None))
        self.lbl_keys_allowed.setText(_translate("dlg_frame", "Allowed keys:", None))
        self.lbl_keys_selected.setText(_translate("dlg_frame", "Selected keys:", None))
        self.gbx_components.setTitle(_translate("dlg_frame", "Components", None))
        self.pbt_new.setText(_translate("dlg_frame", "New", None))
        self.pbt_up.setText(_translate("dlg_frame", "Up", None))
        self.pbt_down.setText(_translate("dlg_frame", "Down", None))
        self.pbt_edit.setText(_translate("dlg_frame", "Edit", None))
        self.pbt_copy.setText(_translate("dlg_frame", "Copy", None))
        self.pbt_remove.setText(_translate("dlg_frame", "Remove", None))
        self.pbt_preview.setText(_translate("dlg_frame", "PreView", None))

