# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files\saccadeApp.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_dlg_saccadeapp(object):
    def setupUi(self):
        self.setObjectName(_fromUtf8("dlg_saccadeapp"))
        self.resize(530, 350)
        self.setMinimumSize(QtCore.QSize(530, 350))
        self.setMaximumSize(QtCore.QSize(530, 850))
        self.vly_01 = QtGui.QWidget(self)
        self.vly_01.setObjectName(_fromUtf8("vly_01"))
        self.verticalLayout = QtGui.QVBoxLayout(self.vly_01)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tab_main = QtGui.QTabWidget(self.vly_01)
        self.tab_main.setMinimumSize(QtCore.QSize(0, 0))
        self.tab_main.setObjectName(_fromUtf8("tab_main"))
        self.wdg_experiment = QtGui.QWidget()
        self.wdg_experiment.setObjectName(_fromUtf8("wdg_experiment"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.wdg_experiment)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.trv_experiment = QtGui.QTreeView(self.wdg_experiment)
        self.trv_experiment.setMinimumSize(QtCore.QSize(250, 200))
        self.trv_experiment.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.trv_experiment.setObjectName(_fromUtf8("trv_experiment"))
        self.horizontalLayout.addWidget(self.trv_experiment)
        self.vly_02 = QtGui.QVBoxLayout()
        self.vly_02.setSpacing(3)
        self.vly_02.setObjectName(_fromUtf8("vly_02"))
        self.pbt_experiment_new = QtGui.QPushButton(self.wdg_experiment)
        self.pbt_experiment_new.setMinimumSize(QtCore.QSize(80, 25))
        self.pbt_experiment_new.setMaximumSize(QtCore.QSize(16777215, 25))
        self.pbt_experiment_new.setObjectName(_fromUtf8("pbt_experiment_new"))
        self.vly_02.addWidget(self.pbt_experiment_new)
        self.pbt_experiment_edit = QtGui.QPushButton(self.wdg_experiment)
        self.pbt_experiment_edit.setMinimumSize(QtCore.QSize(80, 25))
        self.pbt_experiment_edit.setMaximumSize(QtCore.QSize(16777215, 25))
        self.pbt_experiment_edit.setObjectName(_fromUtf8("pbt_experiment_edit"))
        self.vly_02.addWidget(self.pbt_experiment_edit)
        self.pbt_experiment_copy = QtGui.QPushButton(self.wdg_experiment)
        self.pbt_experiment_copy.setMinimumSize(QtCore.QSize(0, 25))
        self.pbt_experiment_copy.setMaximumSize(QtCore.QSize(16777215, 25))
        self.pbt_experiment_copy.setObjectName(_fromUtf8("pbt_experiment_copy"))
        self.vly_02.addWidget(self.pbt_experiment_copy)
        self.pbt_experiment_remove = QtGui.QPushButton(self.wdg_experiment)
        self.pbt_experiment_remove.setMinimumSize(QtCore.QSize(80, 25))
        self.pbt_experiment_remove.setMaximumSize(QtCore.QSize(16777215, 25))
        self.pbt_experiment_remove.setObjectName(_fromUtf8("pbt_experiment_remove"))
        self.vly_02.addWidget(self.pbt_experiment_remove)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vly_02.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.vly_02)
        self.tab_main.addTab(self.wdg_experiment, _fromUtf8(""))
        self.wdg_configuration = QtGui.QWidget()
        self.wdg_configuration.setObjectName(_fromUtf8("wdg_configuration"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.wdg_configuration)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gbx_configuration_basic = QtGui.QGroupBox(self.wdg_configuration)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbx_configuration_basic.sizePolicy().hasHeightForWidth())
        self.gbx_configuration_basic.setSizePolicy(sizePolicy)
        self.gbx_configuration_basic.setObjectName(_fromUtf8("gbx_configuration_basic"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gbx_configuration_basic)
        self.gridLayout_2.setHorizontalSpacing(5)
        self.gridLayout_2.setVerticalSpacing(3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lbl_path_database = QtGui.QLabel(self.gbx_configuration_basic)
        self.lbl_path_database.setMinimumSize(QtCore.QSize(0, 25))
        self.lbl_path_database.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lbl_path_database.setObjectName(_fromUtf8("lbl_path_database"))
        self.gridLayout_2.addWidget(self.lbl_path_database, 0, 0, 1, 1)
        self.lbl_monitor_center = QtGui.QLabel(self.gbx_configuration_basic)
        self.lbl_monitor_center.setMinimumSize(QtCore.QSize(0, 25))
        self.lbl_monitor_center.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lbl_monitor_center.setObjectName(_fromUtf8("lbl_monitor_center"))
        self.gridLayout_2.addWidget(self.lbl_monitor_center, 1, 0, 1, 1)
        self.led_path_database = QtGui.QLineEdit(self.gbx_configuration_basic)
        self.led_path_database.setMinimumSize(QtCore.QSize(150, 25))
        self.led_path_database.setMaximumSize(QtCore.QSize(16777215, 25))
        self.led_path_database.setText(_fromUtf8(""))
        self.led_path_database.setObjectName(_fromUtf8("led_path_database"))
        self.gridLayout_2.addWidget(self.led_path_database, 0, 1, 1, 1)
        self.pbt_path_database = QtGui.QPushButton(self.gbx_configuration_basic)
        self.pbt_path_database.setMinimumSize(QtCore.QSize(80, 25))
        self.pbt_path_database.setMaximumSize(QtCore.QSize(80, 25))
        self.pbt_path_database.setObjectName(_fromUtf8("pbt_path_database"))
        self.gridLayout_2.addWidget(self.pbt_path_database, 0, 2, 1, 1)
        self.pbt_monitor_center = QtGui.QPushButton(self.gbx_configuration_basic)
        self.pbt_monitor_center.setMinimumSize(QtCore.QSize(150, 25))
        self.pbt_monitor_center.setMaximumSize(QtCore.QSize(16777215, 25))
        self.pbt_monitor_center.setObjectName(_fromUtf8("pbt_monitor_center"))
        self.gridLayout_2.addWidget(self.pbt_monitor_center, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.gbx_configuration_basic)
        self.gbx_configuration_profile = QtGui.QGroupBox(self.wdg_configuration)
        self.gbx_configuration_profile.setObjectName(_fromUtf8("gbx_configuration_profile"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.gbx_configuration_profile)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lsv_configuration = QtGui.QListView(self.gbx_configuration_profile)
        self.lsv_configuration.setMinimumSize(QtCore.QSize(230, 150))
        self.lsv_configuration.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.lsv_configuration.setObjectName(_fromUtf8("lsv_configuration"))
        self.horizontalLayout_2.addWidget(self.lsv_configuration)
        self.vly_03 = QtGui.QVBoxLayout()
        self.vly_03.setSpacing(3)
        self.vly_03.setObjectName(_fromUtf8("vly_03"))
        self.pbt_configuration_new = QtGui.QPushButton(self.gbx_configuration_profile)
        self.pbt_configuration_new.setMinimumSize(QtCore.QSize(80, 25))
        self.pbt_configuration_new.setMaximumSize(QtCore.QSize(16777215, 25))
        self.pbt_configuration_new.setObjectName(_fromUtf8("pbt_configuration_new"))
        self.vly_03.addWidget(self.pbt_configuration_new)
        self.pbt_configuration_edit = QtGui.QPushButton(self.gbx_configuration_profile)
        self.pbt_configuration_edit.setMinimumSize(QtCore.QSize(80, 25))
        self.pbt_configuration_edit.setMaximumSize(QtCore.QSize(16777215, 25))
        self.pbt_configuration_edit.setObjectName(_fromUtf8("pbt_configuration_edit"))
        self.vly_03.addWidget(self.pbt_configuration_edit)
        self.pbt_configuration_remove = QtGui.QPushButton(self.gbx_configuration_profile)
        self.pbt_configuration_remove.setMinimumSize(QtCore.QSize(80, 25))
        self.pbt_configuration_remove.setMaximumSize(QtCore.QSize(16777215, 25))
        self.pbt_configuration_remove.setObjectName(_fromUtf8("pbt_configuration_remove"))
        self.vly_03.addWidget(self.pbt_configuration_remove)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vly_03.addItem(spacerItem1)
        self.horizontalLayout_2.addLayout(self.vly_03)
        self.verticalLayout_2.addWidget(self.gbx_configuration_profile)
        self.tab_main.addTab(self.wdg_configuration, _fromUtf8(""))
        self.wdg_execution = QtGui.QWidget()
        self.wdg_execution.setObjectName(_fromUtf8("wdg_execution"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.wdg_execution)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.hly_01 = QtGui.QHBoxLayout()
        self.hly_01.setObjectName(_fromUtf8("hly_01"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hly_01.addItem(spacerItem3)
        self.gbx_execution = QtGui.QGroupBox(self.wdg_execution)
        self.gbx_execution.setMinimumSize(QtCore.QSize(0, 160))
        self.gbx_execution.setMaximumSize(QtCore.QSize(16777215, 160))
        self.gbx_execution.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.gbx_execution.setTitle(_fromUtf8(""))
        self.gbx_execution.setAlignment(QtCore.Qt.AlignCenter)
        self.gbx_execution.setObjectName(_fromUtf8("gbx_execution"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.gbx_execution)
        self.verticalLayout_4.setSpacing(5)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.fly_01 = QtGui.QFormLayout()
        self.fly_01.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.fly_01.setHorizontalSpacing(5)
        self.fly_01.setVerticalSpacing(3)
        self.fly_01.setObjectName(_fromUtf8("fly_01"))
        self.lbl_execution_experiment = QtGui.QLabel(self.gbx_execution)
        self.lbl_execution_experiment.setMinimumSize(QtCore.QSize(0, 25))
        self.lbl_execution_experiment.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lbl_execution_experiment.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_execution_experiment.setObjectName(_fromUtf8("lbl_execution_experiment"))
        self.fly_01.setWidget(0, QtGui.QFormLayout.LabelRole, self.lbl_execution_experiment)
        self.cmb_execution_experiment = QtGui.QComboBox(self.gbx_execution)
        self.cmb_execution_experiment.setMinimumSize(QtCore.QSize(200, 25))
        self.cmb_execution_experiment.setMaximumSize(QtCore.QSize(16777215, 25))
        self.cmb_execution_experiment.setObjectName(_fromUtf8("cmb_execution_experiment"))
        self.fly_01.setWidget(0, QtGui.QFormLayout.FieldRole, self.cmb_execution_experiment)
        self.lbl_execution_profile = QtGui.QLabel(self.gbx_execution)
        self.lbl_execution_profile.setMinimumSize(QtCore.QSize(0, 25))
        self.lbl_execution_profile.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lbl_execution_profile.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_execution_profile.setObjectName(_fromUtf8("lbl_execution_profile"))
        self.fly_01.setWidget(1, QtGui.QFormLayout.LabelRole, self.lbl_execution_profile)
        self.cmb_execution_profile = QtGui.QComboBox(self.gbx_execution)
        self.cmb_execution_profile.setMinimumSize(QtCore.QSize(200, 25))
        self.cmb_execution_profile.setMaximumSize(QtCore.QSize(16777215, 25))
        self.cmb_execution_profile.setObjectName(_fromUtf8("cmb_execution_profile"))
        self.fly_01.setWidget(1, QtGui.QFormLayout.FieldRole, self.cmb_execution_profile)
        self.cbt_execution_save = QtGui.QCheckBox(self.gbx_execution)
        self.cbt_execution_save.setObjectName(_fromUtf8("cbt_execution_save"))
        self.fly_01.setWidget(2, QtGui.QFormLayout.FieldRole, self.cbt_execution_save)
        self.verticalLayout_4.addLayout(self.fly_01)
        self.hly_02 = QtGui.QHBoxLayout()
        self.hly_02.setSpacing(0)
        self.hly_02.setObjectName(_fromUtf8("hly_02"))
        self.pbt_execute = QtGui.QPushButton(self.gbx_execution)
        self.pbt_execute.setMinimumSize(QtCore.QSize(80, 40))
        self.pbt_execute.setMaximumSize(QtCore.QSize(100, 40))
        self.pbt_execute.setObjectName(_fromUtf8("pbt_execute"))
        self.hly_02.addWidget(self.pbt_execute)
        self.verticalLayout_4.addLayout(self.hly_02)
        self.hly_01.addWidget(self.gbx_execution)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hly_01.addItem(spacerItem4)
        self.verticalLayout_3.addLayout(self.hly_01)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem5)
        self.tab_main.addTab(self.wdg_execution, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tab_main)
        self.setCentralWidget(self.vly_01)
        self.mbr_menu = QtGui.QMenuBar(self)
        self.mbr_menu.setGeometry(QtCore.QRect(0, 0, 530, 21))
        self.mbr_menu.setObjectName(_fromUtf8("mbr_menu"))
        self.mnu_file = QtGui.QMenu(self.mbr_menu)
        self.mnu_file.setObjectName(_fromUtf8("mnu_file"))
        self.mnu_help = QtGui.QMenu(self.mbr_menu)
        self.mnu_help.setObjectName(_fromUtf8("mnu_help"))
        self.setMenuBar(self.mbr_menu)
        self.mac_exit = QtGui.QAction(self)
        self.mac_exit.setObjectName(_fromUtf8("mac_exit"))
        self.mac_documentation = QtGui.QAction(self)
        self.mac_documentation.setObjectName(_fromUtf8("mac_documentation"))
        self.mac_about = QtGui.QAction(self)
        self.mac_about.setObjectName(_fromUtf8("mac_about"))
        self.actionSome_shit = QtGui.QAction(self)
        self.actionSome_shit.setObjectName(_fromUtf8("actionSome_shit"))
        self.mnu_file.addAction(self.mac_exit)
        self.mnu_help.addAction(self.mac_documentation)
        self.mnu_help.addSeparator()
        self.mnu_help.addAction(self.mac_about)
        self.mbr_menu.addAction(self.mnu_file.menuAction())
        self.mbr_menu.addAction(self.mnu_help.menuAction())

        self.retranslateUi()
        self.tab_main.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        self.setWindowTitle(_translate("dlg_saccadeapp", "saccadeApp", None))
        self.pbt_experiment_new.setText(_translate("dlg_saccadeapp", "New", None))
        self.pbt_experiment_edit.setText(_translate("dlg_saccadeapp", "Edit", None))
        self.pbt_experiment_copy.setText(_translate("dlg_saccadeapp", "Copy", None))
        self.pbt_experiment_remove.setText(_translate("dlg_saccadeapp", "Remove", None))
        self.tab_main.setTabText(self.tab_main.indexOf(self.wdg_experiment), _translate("dlg_saccadeapp", "Experiments", None))
        self.gbx_configuration_basic.setTitle(_translate("dlg_saccadeapp", "Basic Configuration", None))
        self.lbl_path_database.setText(_translate("dlg_saccadeapp", "Database file:", None))
        self.lbl_monitor_center.setText(_translate("dlg_saccadeapp", "Monitor Center:", None))
        self.pbt_path_database.setText(_translate("dlg_saccadeapp", "Browse...", None))
        self.pbt_monitor_center.setText(_translate("dlg_saccadeapp", "Open", None))
        self.gbx_configuration_profile.setTitle(_translate("dlg_saccadeapp", "Configuration Profiles", None))
        self.pbt_configuration_new.setText(_translate("dlg_saccadeapp", "New", None))
        self.pbt_configuration_edit.setText(_translate("dlg_saccadeapp", "Edit", None))
        self.pbt_configuration_remove.setText(_translate("dlg_saccadeapp", "Remove", None))
        self.tab_main.setTabText(self.tab_main.indexOf(self.wdg_configuration), _translate("dlg_saccadeapp", "Configuration", None))
        self.lbl_execution_experiment.setText(_translate("dlg_saccadeapp", "Experiment:", None))
        self.lbl_execution_profile.setText(_translate("dlg_saccadeapp", "Configuration:", None))
        self.cbt_execution_save.setText(_translate("dlg_saccadeapp", "Save experiment frames", None))
        self.pbt_execute.setText(_translate("dlg_saccadeapp", "Execute", None))
        self.tab_main.setTabText(self.tab_main.indexOf(self.wdg_execution), _translate("dlg_saccadeapp", "Execution", None))
        self.mnu_file.setTitle(_translate("dlg_saccadeapp", "File", None))
        self.mnu_help.setTitle(_translate("dlg_saccadeapp", "Help", None))
        self.mac_exit.setText(_translate("dlg_saccadeapp", "Exit", None))
        self.mac_documentation.setText(_translate("dlg_saccadeapp", "Documentation", None))
        self.mac_about.setText(_translate("dlg_saccadeapp", "About", None))
        self.actionSome_shit.setText(_translate("dlg_saccadeapp", "Some shit", None))

