# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files\test.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_dlg_test(object):
    def setupUi(self):
        self.setObjectName(_fromUtf8("dlg_test"))
        self.resize(530, 500)
        self.setMinimumSize(QtCore.QSize(530, 380))
        self.setMaximumSize(QtCore.QSize(530, 850))
        self.verticalLayout = QtGui.QVBoxLayout(self)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gbx_test = QtGui.QGroupBox(self)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbx_test.sizePolicy().hasHeightForWidth())
        self.gbx_test.setSizePolicy(sizePolicy)
        self.gbx_test.setMinimumSize(QtCore.QSize(0, 145))
        self.gbx_test.setMaximumSize(QtCore.QSize(16777215, 145))
        self.gbx_test.setObjectName(_fromUtf8("gbx_test"))
        self.formLayout_2 = QtGui.QFormLayout(self.gbx_test)
        self.formLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.formLayout_2.setHorizontalSpacing(5)
        self.formLayout_2.setVerticalSpacing(3)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.lbl_name = QtGui.QLabel(self.gbx_test)
        self.lbl_name.setMinimumSize(QtCore.QSize(70, 25))
        self.lbl_name.setMaximumSize(QtCore.QSize(70, 25))
        self.lbl_name.setBaseSize(QtCore.QSize(0, 0))
        self.lbl_name.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_name.setObjectName(_fromUtf8("lbl_name"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.lbl_name)
        self.led_name = QtGui.QLineEdit(self.gbx_test)
        self.led_name.setMinimumSize(QtCore.QSize(0, 25))
        self.led_name.setBaseSize(QtCore.QSize(0, 0))
        self.led_name.setMaxLength(50)
        self.led_name.setObjectName(_fromUtf8("led_name"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.led_name)
        self.ted_description = QtGui.QPlainTextEdit(self.gbx_test)
        self.ted_description.setMinimumSize(QtCore.QSize(0, 50))
        self.ted_description.setMaximumSize(QtCore.QSize(16777215, 50))
        self.ted_description.setObjectName(_fromUtf8("ted_description"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.ted_description)
        self.lbl_quantity = QtGui.QLabel(self.gbx_test)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_quantity.sizePolicy().hasHeightForWidth())
        self.lbl_quantity.setSizePolicy(sizePolicy)
        self.lbl_quantity.setMinimumSize(QtCore.QSize(70, 25))
        self.lbl_quantity.setMaximumSize(QtCore.QSize(70, 25))
        self.lbl_quantity.setBaseSize(QtCore.QSize(0, 0))
        self.lbl_quantity.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_quantity.setObjectName(_fromUtf8("lbl_quantity"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.lbl_quantity)
        self.isb_quantity = QtGui.QSpinBox(self.gbx_test)
        self.isb_quantity.setMinimumSize(QtCore.QSize(0, 25))
        self.isb_quantity.setMaximumSize(QtCore.QSize(65, 25))
        self.isb_quantity.setObjectName(_fromUtf8("isb_quantity"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.isb_quantity)
        self.lbl_description = QtGui.QLabel(self.gbx_test)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_description.sizePolicy().hasHeightForWidth())
        self.lbl_description.setSizePolicy(sizePolicy)
        self.lbl_description.setMinimumSize(QtCore.QSize(70, 25))
        self.lbl_description.setMaximumSize(QtCore.QSize(70, 25))
        self.lbl_description.setBaseSize(QtCore.QSize(0, 0))
        self.lbl_description.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_description.setObjectName(_fromUtf8("lbl_description"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.lbl_description)
        self.verticalLayout.addWidget(self.gbx_test)
        self.gbx_frames = QtGui.QGroupBox(self)
        self.gbx_frames.setMinimumSize(QtCore.QSize(0, 180))
        self.gbx_frames.setObjectName(_fromUtf8("gbx_frames"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.gbx_frames)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tbv_frames = QtGui.QTableView(self.gbx_frames)
        self.tbv_frames.setMinimumSize(QtCore.QSize(380, 120))
        self.tbv_frames.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tbv_frames.setObjectName(_fromUtf8("tbv_frames"))
        self.horizontalLayout.addWidget(self.tbv_frames)
        self.vly_01 = QtGui.QVBoxLayout()
        self.vly_01.setSpacing(3)
        self.vly_01.setObjectName(_fromUtf8("vly_01"))
        self.pbt_new = QtGui.QPushButton(self.gbx_frames)
        self.pbt_new.setMinimumSize(QtCore.QSize(80, 25))
        self.pbt_new.setMaximumSize(QtCore.QSize(16777215, 25))
        self.pbt_new.setObjectName(_fromUtf8("pbt_new"))
        self.vly_01.addWidget(self.pbt_new)
        self.hly_01 = QtGui.QHBoxLayout()
        self.hly_01.setSpacing(4)
        self.hly_01.setObjectName(_fromUtf8("hly_01"))
        self.pbt_up = QtGui.QPushButton(self.gbx_frames)
        self.pbt_up.setMinimumSize(QtCore.QSize(38, 25))
        self.pbt_up.setMaximumSize(QtCore.QSize(38, 25))
        self.pbt_up.setObjectName(_fromUtf8("pbt_up"))
        self.hly_01.addWidget(self.pbt_up)
        self.pbt_down = QtGui.QPushButton(self.gbx_frames)
        self.pbt_down.setMinimumSize(QtCore.QSize(38, 25))
        self.pbt_down.setMaximumSize(QtCore.QSize(38, 25))
        self.pbt_down.setObjectName(_fromUtf8("pbt_down"))
        self.hly_01.addWidget(self.pbt_down)
        self.vly_01.addLayout(self.hly_01)
        self.pbt_edit = QtGui.QPushButton(self.gbx_frames)
        self.pbt_edit.setMinimumSize(QtCore.QSize(80, 25))
        self.pbt_edit.setMaximumSize(QtCore.QSize(16777215, 25))
        self.pbt_edit.setObjectName(_fromUtf8("pbt_edit"))
        self.vly_01.addWidget(self.pbt_edit)
        self.pbt_copy = QtGui.QPushButton(self.gbx_frames)
        self.pbt_copy.setMinimumSize(QtCore.QSize(0, 25))
        self.pbt_copy.setMaximumSize(QtCore.QSize(16777215, 25))
        self.pbt_copy.setObjectName(_fromUtf8("pbt_copy"))
        self.vly_01.addWidget(self.pbt_copy)
        self.pbt_remove = QtGui.QPushButton(self.gbx_frames)
        self.pbt_remove.setMinimumSize(QtCore.QSize(80, 25))
        self.pbt_remove.setMaximumSize(QtCore.QSize(16777215, 25))
        self.pbt_remove.setObjectName(_fromUtf8("pbt_remove"))
        self.vly_01.addWidget(self.pbt_remove)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vly_01.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.vly_01)
        self.verticalLayout.addWidget(self.gbx_frames)
        self.hly_02 = QtGui.QHBoxLayout()
        self.hly_02.setObjectName(_fromUtf8("hly_02"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hly_02.addItem(spacerItem1)
        self.pbt_preview = QtGui.QPushButton(self)
        self.pbt_preview.setMinimumSize(QtCore.QSize(155, 25))
        self.pbt_preview.setMaximumSize(QtCore.QSize(155, 25))
        self.pbt_preview.setObjectName(_fromUtf8("pbt_preview"))
        self.hly_02.addWidget(self.pbt_preview)
        self.verticalLayout.addLayout(self.hly_02)
        self.bbt_save = QtGui.QDialogButtonBox(self)
        self.bbt_save.setMinimumSize(QtCore.QSize(0, 25))
        self.bbt_save.setMaximumSize(QtCore.QSize(16777215, 25))
        self.bbt_save.setOrientation(QtCore.Qt.Horizontal)
        self.bbt_save.setStandardButtons(QtGui.QDialogButtonBox.Close|QtGui.QDialogButtonBox.Save)
        self.bbt_save.setObjectName(_fromUtf8("bbt_save"))
        self.verticalLayout.addWidget(self.bbt_save)

        self.retranslateUi()
        QtCore.QObject.connect(self.bbt_save, QtCore.SIGNAL(_fromUtf8("accepted()")), self.accept)
        QtCore.QObject.connect(self.bbt_save, QtCore.SIGNAL(_fromUtf8("rejected()")), self.reject)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        self.setWindowTitle(_translate("dlg_test", "Test", None))
        self.gbx_test.setTitle(_translate("dlg_test", "Test", None))
        self.lbl_name.setText(_translate("dlg_test", "Name:", None))
        self.lbl_quantity.setText(_translate("dlg_test", "Quantity:", None))
        self.lbl_description.setText(_translate("dlg_test", "Description:", None))
        self.gbx_frames.setTitle(_translate("dlg_test", "Frames", None))
        self.pbt_new.setText(_translate("dlg_test", "New", None))
        self.pbt_up.setText(_translate("dlg_test", "Up", None))
        self.pbt_down.setText(_translate("dlg_test", "Down", None))
        self.pbt_edit.setText(_translate("dlg_test", "Edit", None))
        self.pbt_copy.setText(_translate("dlg_test", "Copy", None))
        self.pbt_remove.setText(_translate("dlg_test", "Remove", None))
        self.pbt_preview.setText(_translate("dlg_test", "PreView", None))

