-- MySQL Script generated by MySQL Workbench
-- jue 25 ene 2018 02:12:29 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema saccadedb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema saccadedb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `saccadedb` DEFAULT CHARACTER SET latin1 COLLATE latin1_spanish_ci ;
USE `saccadedb` ;

-- -----------------------------------------------------
-- Table `saccadedb`.`test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saccadedb`.`test` (
  `tes_code` VARCHAR(10) NOT NULL,
  `tes_title` VARCHAR(100) NOT NULL,
  `tes_version` VARCHAR(10) NOT NULL,
  `tes_description` MEDIUMTEXT NULL,
  `tes_datecreation` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `tes_dateupdate` TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`tes_title`, `tes_version`),
  UNIQUE INDEX `tes_code_UNIQUE` (`tes_code` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `saccadedb`.`experiment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saccadedb`.`experiment` (
  `exp_code` VARCHAR(10) NOT NULL,
  `exp_title` VARCHAR(100) NOT NULL,
  `exp_version` VARCHAR(10) NOT NULL,
  `exp_description` MEDIUMTEXT NULL,
  `exp_comment` MEDIUMTEXT NULL,
  `exp_datecreation` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `exp_dateupdate` TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`exp_title`, `exp_version`),
  UNIQUE INDEX `exp_code_UNIQUE` (`exp_code` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `saccadedb`.`exp_dialog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saccadedb`.`exp_dialog` (
  `exp_code` VARCHAR(10) NOT NULL,
  `dia_enable` TINYINT NOT NULL DEFAULT 1,
  `dia_askage` TINYINT NOT NULL DEFAULT 1,
  `dia_askgender` TINYINT NOT NULL DEFAULT 1,
  `dia_askglasses` TINYINT NOT NULL DEFAULT 1,
  `dia_askeyecolor` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`exp_code`),
  CONSTRAINT `fk_exp_dia`
    FOREIGN KEY (`exp_code`)
    REFERENCES `saccadedb`.`experiment` (`exp_code`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `saccadedb`.`exp_tes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saccadedb`.`exp_tes` (
  `tes_code` VARCHAR(10) NOT NULL,
  `exp_code` VARCHAR(10) NOT NULL,
  `exp_tes_id` INT NOT NULL DEFAULT 1,
  `exp_tes_quantity` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`tes_code`, `exp_code`, `exp_tes_id`),
  INDEX `idx_exp_tes` (`exp_code` ASC),
  INDEX `idx_tes_exp` (`tes_code` ASC),
  CONSTRAINT `fk_exp_tes`
    FOREIGN KEY (`exp_code`)
    REFERENCES `saccadedb`.`experiment` (`exp_code`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tes_exp`
    FOREIGN KEY (`tes_code`)
    REFERENCES `saccadedb`.`test` (`tes_code`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `saccadedb`.`exp_config`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saccadedb`.`exp_config` (
  `exp_code` VARCHAR(10) NOT NULL,
  `con_spacetostart` TINYINT NOT NULL DEFAULT 0,
  `con_israndom` TINYINT NOT NULL DEFAULT 0,
  `con_isrest` TINYINT NOT NULL DEFAULT 0,
  `con_restperiod` INT NOT NULL DEFAULT 0,
  `con_resttime` FLOAT NOT NULL DEFAULT 0.0,
  PRIMARY KEY (`exp_code`),
  CONSTRAINT `fk_exp_con`
    FOREIGN KEY (`exp_code`)
    REFERENCES `saccadedb`.`experiment` (`exp_code`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `saccadedb`.`tes_frame`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saccadedb`.`tes_frame` (
  `tes_code` VARCHAR(10) NOT NULL,
  `fra_id` INT NOT NULL DEFAULT 1,
  `fra_color` VARCHAR(20) NOT NULL DEFAULT 'black',
  `fra_istask` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`tes_code`, `fra_id`),
  INDEX `idx_tes_fra` (`tes_code` ASC),
  CONSTRAINT `fk_tes_fra`
    FOREIGN KEY (`tes_code`)
    REFERENCES `saccadedb`.`test` (`tes_code`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `saccadedb`.`tes_fra_time`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saccadedb`.`tes_fra_time` (
  `tes_code` VARCHAR(10) NOT NULL,
  `fra_id` INT NOT NULL DEFAULT 1,
  `tim_time` FLOAT NOT NULL DEFAULT 0.0,
  PRIMARY KEY (`tes_code`, `fra_id`),
  CONSTRAINT `fk_tes_fra_tim`
    FOREIGN KEY (`tes_code` , `fra_id`)
    REFERENCES `saccadedb`.`tes_frame` (`tes_code` , `fra_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `saccadedb`.`tes_fra_task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saccadedb`.`tes_fra_task` (
  `tes_code` VARCHAR(10) NOT NULL,
  `fra_id` INT NOT NULL DEFAULT 1,
  `tas_keysall` TEXT NOT NULL,
  `tas_keyssel` TEXT NOT NULL,
  PRIMARY KEY (`tes_code`, `fra_id`),
  CONSTRAINT `fk_tes_fra_tas`
    FOREIGN KEY (`tes_code` , `fra_id`)
    REFERENCES `saccadedb`.`tes_frame` (`tes_code` , `fra_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `saccadedb`.`object`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saccadedb`.`object` (
  `tes_code` VARCHAR(10) NOT NULL,
  `fra_id` INT NOT NULL DEFAULT 1,
  `obj_id` INT NOT NULL DEFAULT 1,
  `obj_name` VARCHAR(50) NULL,
  `obj_units` VARCHAR(10) NOT NULL DEFAULT 'deg',
  `obj_posx` FLOAT NOT NULL DEFAULT 0.0,
  `obj_posy` FLOAT NOT NULL DEFAULT 0.0,
  `obj_ori` FLOAT NOT NULL DEFAULT 0.0,
  `obj_isimg` TINYINT NOT NULL DEFAULT 0,
  `obj_image` BLOB NULL,
  `obj_shape` VARCHAR(20) NOT NULL DEFAULT 'square',
  `obj_color` VARCHAR(20) NOT NULL DEFAULT 'white',
  PRIMARY KEY (`tes_code`, `fra_id`, `obj_id`),
  INDEX `idx_tes_fra_obj` (`tes_code` ASC, `fra_id` ASC),
  CONSTRAINT `fk_tes_fra_obj`
    FOREIGN KEY (`tes_code` , `fra_id`)
    REFERENCES `saccadedb`.`tes_frame` (`tes_code` , `fra_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `saccadedb`.`master`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saccadedb`.`master` (
  `mas_title` VARCHAR(100) NOT NULL,
  `mas_screen` INT NOT NULL DEFAULT 0,
  `mas_tracker` INT NOT NULL DEFAULT 0,
  `mas_monitor` VARCHAR(50) NOT NULL DEFAULT 'default',
  `mas_savepath` VARCHAR(200) NOT NULL DEFAULT './events',
  PRIMARY KEY (`mas_title`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
